# Generated by Django 3.2.18 on 2023-04-04 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
